---
dimensions:
  - name: time
    size: 8
  - name: elements
    size: 256

datasets:
  - name: a
    dims: [elements]
    dtype: f32
  - name: b
    dims: [elements]
    dtype: f32
  - name: c
    dims: [elements]
    dtype: f16
  - name: d
    dims: [time, elements]
    dtype: u8
