# Configures telescope coordinates used in solar transit calculations
[telescope]
latitude = 49.320_709_219_4
longitude = -119.623_677_431_0
altitude = 555.372

# Specifies solar zeroing system interactions
[zeroing]
downtime = 3600 # seconds
hostname = "upgrade-gpu1:12048"
target = "enabled"
first_stage = "rfi_first_stage_enabled"
second_stage = "rfi_second_stage_enabled"
